### ISSUE TITLE
As a cluster operator, I want to evaluate and determine available compute options so that I can be confident my solution leverages the option best suited for the workloads that will run on the cluster

### ISSUE THREAD

**Issue by zmmille2** [zmmille2/playground#37]
## Acceptance Criteria
- [ ] Decision record documenting compute requirements and chosen compute option
## Tasks
- [ ] Define compute requirements
- [ ] Evaluate compute options
- [ ] If applicable, evaluate virtualization options
